# Simple workflow for deploying static content from 4_CICD to GitHub Pages
name: Deploy 4_CICD Content to Pages

on:
  # Triggers the workflow when changes are pushed to the 4_CICD directory on the main branch
  push:
    branches: ['main']
    paths:
      - '4_CICD/**'

  # Allows manual triggering of the workflow
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures only one deployment runs at a time
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Prepares the content from 4_CICD for deployment
      - name: Prepare deployment content
        run: |
          mkdir -p deployment
          cp -r 4_CICD/* deployment/

      # Uploads the prepared content as an artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deployment'

      # Deploys the content to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4